### PR TITLE
feat(download): add progress bar

### PR DESCRIPTION
**Pull request by amrbashir**

### CODE REVIEW

**Comment by amrbashir** [comment]
@FabianLars could you double check if this behavior is good or should I convert it to a dialog instead?

**Comment by FabianLars** [comment]
I like it! And it works perfect, as long as you don't expand the details :/ Then it looks like this
grafik

p.s. i think i'd prefer having no download-specific progress bar over a custom dialog if this solution here doesn't work out. I don't feel like a custom dialog would be _much_ better received than the webview2 dialog we once had before we added the /silent option.
(Edit: Did i misunderstand what dialog is?)

**Comment by amrbashir** [comment]
a dialog would be like this 
image

I will see if I can move the progress bar right below the main bar and resize the details pane

**Comment by amrbashir** [comment]
@FabianLars  could you give this another try? the details section now clears a space for the download progress bar

**Comment by FabianLars** [comment]
Way better! Looks like this while downloading

grafik

Now there's just a artifact left when the download is done and it executes the wv2 installer. Looks like the artifacts goes away once it prints `WebView2 installed successfully` the artifact.

grafik

**Comment by amrbashir** [comment]
could you try again, I believe these artifacts should be fixed now (at least on my machine)

**Comment by FabianLars** [comment]
Still the same once it starts installing WebView2 (until it finishes installing it):

grafik

Could be worse :D

**Comment by amrbashir** [comment]
Can you test it one more time and I will just merge it as is.

**Comment by FabianLars** [comment]
working perfectly now, nice!

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
